apiVersion: v1
data:
  auth-password: bXktc2VjcmV0LXB3
  root-password: c2VjdXJlLXJvb3QtcHc=
  secret-key: eGNvMHNyMGZoNGU1MngwM2c5bXY=
kind: Secret
metadata:
  creationTimestamp: "2026-07-27T21:08:42Z"
  name: mysql-secret
  namespace: default
  resourceVersion: "1401"
  uid: e0f13fcf-05cf-48ea-bfdc-0832d4f628c3
type: Opaque
