apiVersion: v1
data:
  apikey: NjQ4NGZjMjQ4YW1zaGEyYjFjOGY3NWM4ZjIwZnAxNTRkZGRqc245NGZmOGExZGY3OTI=
kind: Secret
metadata:
  creationTimestamp: "2026-07-31T15:19:39Z"
  name: weather
  namespace: default
  resourceVersion: "22025"
  uid: dc0afcbb-9aa1-48a8-aaa3-b9a16e489908
type: Opaque
